name: Build Kernel (violet | KernelSU Next + SUSFS | ZyC Clang)

on:
  push:
    branches:
      - sixteen
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison flex git curl zip unzip \
          make gcc libc6-dev libssl-dev \
          ccache python3

    - name: Download ZyCromerZ Clang 22
      run: |
        curl -L \
        https://github.com/ZyCromerZ/Clang/releases/download/22.0.0git-20250928-release/Clang-22.0.0git-20250928.tar.gz \
        -o clang.tar.gz
        mkdir clang
        tar -xf clang.tar.gz -C clang --strip-components=1

    - name: Setup toolchain env
      run: |
        echo "PATH=$GITHUB_WORKSPACE/clang/bin:$PATH" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "LLVM=1" >> $GITHUB_ENV
        echo "LLVM_IAS=1" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
