name: Extract Patch from Commit

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (sixteen-sukisu)
        uses: actions/checkout@v4
        with:
          ref: sixteen-sukisu
          fetch-depth: 0

      - name: Generate patch from commit
        run: |
          COMMIT=980a0197f572fa0491780a7554d480391ca28aa0
          git format-patch -1 $COMMIT --stdout > backport.patch

      - name: Upload patch
        uses: actions/upload-artifact@v4
        with:
          name: extracted-patch
          path: backport.patch
