name: Extract manual hook 1.6

on:
  push:
    branches:
      - sixteen-sukisu
  workflow_dispatch:
jobs:
  extract:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone empty repo
        run: |
          git init repo
          cd repo
          git remote add origin https://github.com/sidex15/android_kernel_lge_sm8150.git
          git fetch origin 87e6c1fcbd9c007b6a9e34aafdbebc86fd6590f6
          git checkout FETCH_HEAD
          git format-patch -1 HEAD --stdout > commit.patch

      - name: Upload patch
        uses: actions/upload-artifact@v4
        with:
          name: extracted-commit
          path: repo/commit.patch
