name: Extract Patch from Commit

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # مهم جداً حتى نقدر نجيب أي commit

      - name: Generate patch from commit
        run: |
          COMMIT=980a0197f572fa0491780a7554d480391ca28aa0
          git format-patch -1 $COMMIT
          ls -lah *.patch

      - name: Rename patch
        run: |
          mv 0001-*.patch susfs-2.0.0-backport-full.patch

      - name: Upload patch artifact
        uses: actions/upload-artifact@v4
        with:
          name: susfs-2.0.0-backport
          path: susfs-2.0.0-backport-full.patch
