name: act Patch from Commit

on:
  push:
    branches:
      - sixteen-sukisu 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo (sixteen-sukisu)
        uses: actions/checkout@v4
        with:
          ref: sixteen-sukisu
          fetch-depth: 0

      - name: Generate patch from commit
        run: |
          COMMIT=3335650a439a47f528113353b80b50b7908d0621
          git format-patch -1 $COMMIT --stdout > backport.patch

      - name: Upload patch
        uses: actions/upload-artifact@v4
        with:
          name: extracted-patch
          path: backport-susfs-1.5.12.patch
