name: Actions Sanity Check

on:
  push:
    branches:
      - sixteen
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print info
        run: |
          echo "Branch is: $GITHUB_REF"
          echo "GitHub Actions WORKS"

      - name: Done
        run: echo "Workflow finished successfully"
